src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[ORM\Entity(repositoryClass: CommandRepository::class)]
#[HasLifecycleCallbacks]
class Command
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $date;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commands')]
    private $user;

    #[ORM\Column(type: 'float')]
    private $price;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $link;

    #[ORM\ManyToMany(targetEntity: Product::class, inversedBy: 'commands')]
    private $products;

    #[ORM\Column(type: 'json')]
    private $quantity_arr = [];

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        $this->products->removeElement($product);

        return $this;
    }

    #[ORM\PrePersist]
    public function onPrePersist(LifecycleEventArgs $eventArgs)
    {
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(LifecycleEventArgs $eventArgs)
    {
    }

    public function getQuantityArr(): ?array
    {
        return $this->quantity_arr;
    }

    public function setQuantityArr(array $quantity_arr): self
    {
        $this->quantity_arr = $quantity_arr;

        return $this;
    }
}

src/Form/CommandType.php
<?php

namespace App\Form;

use App\Entity\Command;
use App\Entity\Product;
use DateTime;
use Doctrine\DBAL\Types\ArrayType;
use PhpParser\ErrorHandler\Collecting;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'empty_data' => new DateTime()
            ])
            ->add('link', FileType::class, [
                "mapped" => false,
                "required" => false,
            ])
            ->add('user')
            ->add('products', CollectionType::class, [
                'entry_type' => QuantityType::class,
                'entry_options' => ['label' => false],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
        ]);
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use App\Entity\Product;
use App\Form\CommandType;
use App\Form\PanierType;
use App\Repository\CommandRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use App\Helpers\FunctionsHelpers;

#[Route('/command')]
class CommandController extends AbstractController
{

    private $em;
    private $security;

    public function __construct(Security $security, EntityManagerInterface $em)
    {
        $this->security = $security;
        $this->em = $em;
        $this->fh = new FunctionsHelpers($security);
    }

    #[Route('/', name: 'app_command_index', methods: ['GET'])]
    public function index(CommandRepository $commandRepository): Response
    {
        $user = $this->security->getUser();
        if (in_array("ROLE_ADMIN", $user->getRoles())) {
            $commands = $commandRepository->findAll();
        } else {
            $commands = $commandRepository->findBy(["user" => $user->getId()]);
        }
        return $this->render('command/index.html.twig', [
            'commands' => $commands,
        ]);
    }

    #[Route('/new', name: 'app_command_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommandRepository $commandRepository): Response
    {
        $command = new Command();
        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commandRepository->add($command);
            return $this->redirectToRoute('app_command_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('command/new.html.twig', [
            'command' => $command,
            'form' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'app_command_show', methods: ['GET'])]
    public function show(Command $command): Response
    {
        return $this->render('command/show.html.twig', [
            'command' => $command,
        ]);
    }

    #[Route('/edit/{id}/edit', name: 'app_command_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Command $command, CommandRepository $commandRepository): Response
    {
        foreach ($command->getProducts() as $key => $product) {
            $command->removeProduct($product);
            if (isset($command->getQuantityArr()[$product->getId()])) {
                $product->setQuantity($command->getQuantityArr()[$product->getId()]);
            }
            $command->addProduct($product);
        }
        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $quantity = [];
            $price = 0;
            foreach ($command->getProducts() as $product) {
                $price += $product->getPrice() * $product->getQuantity();
                $quantity[$product->getId()] = $product->getQuantity();
                $command->addProduct($product);
            }

            $command->setPrice($price)
                ->setQuantityArr($quantity)
                ->setUser($this->security->getUser())
                ->setDate(new DateTime());

            if ($form['link']->getData()) {
                $file = $form['link']->getData();
                $filename = $this->fh->generateSlug(pathinfo($file->getClientOriginalName())["filename"]) . "." . pathinfo($file->getClientOriginalName())["extension"];
                $file->move("./images", $filename);
                $command->setLink(new File("./images/" . $filename));
            } else {
                $command->setLink(new File($command->getLink()));
            }

            $commandRepository->add($command);
            return $this->redirectToRoute('app_command_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('command/edit.html.twig', [
            'command' => $command,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_command_delete', methods: ['POST'])]
    public function delete(Request $request, Command $command, CommandRepository $commandRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $command->getId(), $request->request->get('_token'))) {
            $commandRepository->remove($command);
        }

        return $this->redirectToRoute('app_command_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route("/panier", name: "see_panier")]
    public function panierAction(SessionInterface $session, Request $request, CommandRepository $commandRepository)
    {
        $command = new Command();
        $panier = $session->get("panier", []);
        foreach ($panier as $key => $product) {
            $command->addProduct($product);
        }
        $form = $this->createForm(PanierType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $command = new Command();
            $panier = $session->get('panier', []);
            $quantity = [];
            $price = 0;
            foreach ($panier as $key => $product) {
                $price += $product->getPrice() * $product->getQuantity();
                $db_product = $this->em->getRepository(Product::class)->find($key);
                $quantity[$key] = $product->getQuantity();
                $command->addProduct($db_product);
            }

            $session->set("panier", []);

            $command->setPrice($price)
                ->setQuantityArr($quantity)
                ->setUser($this->security->getUser())
                ->setDate(new DateTime());

            $commandRepository->add($command);
            return $this->redirectToRoute('app_command_index', [], Response::HTTP_SEE_OTHER);
        }

        $panier = $session->get('panier', []);
        return $this->renderForm("command/panier.html.twig", [
            "command"   => $command,
            "form"      => $form,
        ]);
    }
}

templates/command/_delete_form.html.twig
<form method="post" action="{{ path('app_command_delete', {'id': command.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ command.id) }}">
    <button class="btn">Delete</button>
</form>

templates/command/_form.html.twig
{% block body %}
	<div class="container">
		{{ form_start(form) }}
		<div class="row">
            <div class="col-12">
                {{ form_label(form.link, '', {'label_attr': {'class': 'form-label'}}) }}
				<div class="input-group mb-3 d-block">
					{% if form.link.parent.vars.value.link %}
						<img src="{{ asset(form.link.parent.vars.value.link) }}" class="img-fluid d-block m-auto mb-2" alt="" style="max-width: 100px">
						{{ form_widget(form.link, {'required': false, "attr": {'class': 'w-100 form-control'}}) }}
					{% else %}

						{{ form_widget(form.link, {'attr': {'class': 'form-control w-100'}}) }}
					{% endif %}
				</div>
				<div class="error">{{ form_errors(form.link) }}</div>
			</div>
			<div class="col-6">
				{{ form_label(form.user, '', {'label_attr': {'class': 'form-label'}}) }}
				<div class="input-group mb-3">
                    {{ form_widget(form.user, {'attr': {'class': 'form-select'}}) }}
				</div>
				<div class="error">{{ form_errors(form.user) }}</div>
			</div>
			<div class="col-12">
                {{ form_row(form.products, {'attr': {'class': 'quantity_input'}}) }}
			</div>
			<div class="col-6">
				{{ form_label(form.date, '', {'label_attr': {'class': 'form-label'}}) }}

				<div class="form-group">
					<div class='input-group date' id='datetimepicker1'>
						{{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
				</div>
				<script type="text/javascript">
					$(function () {
$('#datetimepicker1').datetimepicker();
});
				</script>
				<div class="error">{{ form_errors(form.date) }}</div>
			</div>
			<div class="col-12">
				<button type="submit" class="btn btn-primary mt-3">Save</button>
			</div>
		</div>
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/command/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Command{% endblock %}

{% block body %}
    <h1>Edit Command</h1>

    {{ include('command/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_command_index') }}">back to list</a>

    {{ include('command/_delete_form.html.twig') }}
{% endblock %}

templates/command/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Mes commandes
{% endblock %}

{% block body %}
  <h1>
    Mes commandes
  </h1>

  <table class="table">
    <thead>
      <tr>
        <th>
          Id
        </th>
        <th>
          Date
        </th>
        <th>
          Price
        </th>
        <th>
          Link
        </th>
        <th>
          Products
        </th>
        <th>
          actions
        </th>
      </tr>
    </thead>
    <tbody>
      {% for command in commands %}
        <tr>
          <td>
            {{ command.id }}
          </td>
          <td>
            {{ command.date ? command.date|date('Y-m-d') : '' }}
          </td>
          <td>
            {{ command.price }}
          </td>
          <td>
            {{ command.link }}
          </td>
          <td>
            {% for product in command.products %}
              {% for key, quantity in command.quantityArr %}
                {% if product.id == key %}
                  {{ product }} x {{ quantity }}
                {% endif %}
              {% endfor %}
            {% endfor %}
          </td>
          <td>
            <a href="{{
              path(
                'app_command_show',
                {
                  id: command.id
                }
              )
              }}">
              Voir la commande
            </a>
            {% if 'ROLE_ADMIN' in app.user.roles %}
              <a href="{{
                path(
                  'app_command_edit',
                  {
                    id: command.id
                  }
                )
                }}">
                Modifier la commande
              </a>
            {% endif %}
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="5">
            Aucune données
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if 'ROLE_ADMIN' in app.user.roles %}
    <a href="{{ path('app_command_new') }}">Nouvelle commande</a>
  {% endif %}
{% endblock %}

templates/command/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle commande{% endblock %}

{% block body %}
    <h1>Créer une nouvelle commande</h1>

    {{ include('command/_form.html.twig') }}

    <a href="{{ path('app_command_index') }}">Retour a la liste des commandes t</a>
{% endblock %}

templates/command/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block body %}
    <h1>Passer la commande</h1>

    <div class="list-group" id="panier">

        {{ form_start(form) }}
            {% for product in form.products %}
                <div class="d-flex w-100 justify-content-between article">
                    <div class="content">
                        <h5>{{ product.vars.value.label }} <small>x {{product.vars.value.quantity}}</small></h5>
                        <p>{{ product.vars.value.description }}</p>
                        <a href="{{ path("removePanier", {"product" : product.vars.value.id}) }}" class="remove small">Retirer</a>
                    </div>
                    <div class="content">
                        <h5>Quantité : </h5>
                        {{ form_row(product.quantity, {'attr': {'class': 'quantity_input'}}) }}
                    </div>

                    <div >
                        <h5 class="price">{{product.vars.value.price}}€</h5>
                    </div>
                </div>
            {% endfor %}
            <hr>
            <div>
                <h5> Prix total : </h5>
                <div id="total_panier"> 0€ </div>
            </div>
            <hr>

            <div class="confirm d-flex">
                <input type="checkbox" id="confirmation" class='me-1' required>
                <p>Confirmez la commande</p>
            </div>
            <div class="col-12">
				<button type="submit" class="btn btn-primary mt-3">Valider la commande</button>
			</div>  
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/command/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ command.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ command.date ? command.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ command.price }}</td>
            </tr>
            <tr>
                <th>Link</th>
                <td>{{ command.link }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_command_index') }}">Retour a la liste</a>

    <a href="{{ path('app_command_edit', {'id': command.id}) }}">Modifier</a>

    {{ include('command/_delete_form.html.twig') }}
{% endblock %}